### ISSUE TITLE
Qanban-Standalone doesn't start due to JNDI-lookup

### ISSUE THREAD

**Issue by mirhagen** [qbranchcode/Qanban#19] opened 2009-12-18 12:42 UTC
Check when and how InitialContext is loaded

**Comment by xlson** [comment] 2009-12-18 12:46
Stacktrace:
leonard-axelssons-macbook:Downloads leo$ java -Xmx512m -jar qanban-standalone.war
2009-12-18 13:32:37.015::INFO:  Logging to STDERR via org.mortbay.log.StdErrLog
2009-12-18 13:32:37.074::INFO:  jetty-6.1.x
2009-12-18 13:32:37.725::INFO:  Extract file:/Users/leo/Downloads/qanban-standalone.war to /var/folders/65/65qQxHvIFqa+FC8hTdfkrk+++TI/-Tmp-/Jetty_0_0_0_0_8080_qanban.standalone.war____.g1nn2i/webapp
2009-12-18 13:32:39.782::INFO:  NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
log4j:ERROR Error initializing log4j: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
    at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:645)
    at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:288)
    at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:325)
    at javax.naming.InitialContext.lookup(InitialContext.java:392)
    at DataSource$_run_closure3_closure6_closure9.doCall(DataSource.groovy:60)
    at DataSource$_run_closure3_closure6_closure9.doCall(DataSource.groovy)
    at DataSource$_run_closure3_closure6.doCall(DataSource.groovy:54)
    at DataSource$_run_closure3_closure6.doCall(DataSource.groovy)
    at DataSource$_run_closure3.doCall(DataSource.groovy:53)
    at DataSource$_run_closure3.doCall(DataSource.groovy)
    at DataSource.run(DataSource.groovy:32)
    at se.qbranch.standalone.Starter.main(Unknown Source)
2009-12-18 13:32:41.824:/:INFO:  Initializing Spring root WebApplicationContext
2009-12-18 13:32:42.472::WARN:  Failed startup of context org.mortbay.jetty.webapp.WebAppContext@8e2b07b{/,file:/Users/leo/Downloads/qanban-standalone.war}
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
    at java.security.AccessController.doPrivileged(Native Method)
    at se.qbranch.standalone.Starter.main(Unknown Source)
Caused by: javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
    at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:645)
    at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:288)
    at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:325)
    at javax.naming.InitialContext.lookup(InitialContext.java:392)
    at DataSource$_run_closure3_closure6_closure9.doCall(DataSource.groovy:60)
    at DataSource$_run_closure3_closure6_closure9.doCall(DataSource.groovy)
    at DataSource$_run_closure3_closure6.doCall(DataSource.groovy:54)
    at DataSource$_run_closure3_closure6.doCall(DataSource.groovy)
    at DataSource$_run_closure3.doCall(DataSource.groovy:53)
    at DataSource$_run_closure3.doCall(DataSource.groovy)
    at DataSource.run(DataSource.groovy:32)
    ... 2 more
2009-12-18 13:32:42.479::WARN:  Nested in org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial:
javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
    at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:645)
    at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:288)
    at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:325)
    at javax.naming.InitialContext.lookup(InitialContext.java:392)
    at DataSource$_run_closure3_closure6_closure9.doCall(DataSource.groovy:60)
    at DataSource$_run_closure3_closure6_closure9.doCall(DataSource.groovy)
    at DataSource$_run_closure3_closure6.doCall(DataSource.groovy:54)
    at DataSource$_run_closure3_closure6.doCall(DataSource.groovy)
    at DataSource$_run_closure3.doCall(DataSource.groovy:53)
    at DataSource$_run_closure3.doCall(DataSource.groovy)
    at DataSource.run(DataSource.groovy:32)
    at java.security.AccessController.doPrivileged(Native Method)
    at se.qbranch.standalone.Starter.main(Unknown Source)
2009-12-18 13:32:42.488::INFO:  Started SocketConnector@0.0.0.0:8080

**Comment by xlson** [comment] 2009-12-18 12:59
Only applies to master

**Comment by xlson** [comment] 2009-12-18 15:09
Fixed by adding jetty-naming and jetty-plus, request filed in xlson/standalone-war#2

**Comment by xlson** [comment] 2009-12-21 13:01
Fixed in xlson/standalone-war

**Closed as completed by xlson** 2009-12-21 13:01 UTC
Labels: BUG, mirhagen
