### ISSUE TITLE
Log ( and Archive? ) loading

### ISSUE THREAD

**Issue by gardeman** [qbranchcode/Qanban#16] opened 2009-12-18 11:53 UTC
In the log view, the lazy loading of the content doesn't work 9 times out of 10.

Even though the log contains more posts it wont add content when the scroll bar is at the bottom, this probably effects the loading of the archive view as well.

Seen in v 0.1.0.38 ( standalone mode )

**Comment by gardeman** [comment] 2009-12-18 12:23
Seems to work quite well in Google Chrome 4.0.249.30, while it almost never work in Firefox 3.5.5 and Chromium 4.0.267.0. 

( All browsers run under Ubuntu 9.04 )

**Comment by mirhagen** [comment] 2009-12-21 10:23
Log and Archive now loads as intended. Board autorefresh is now working. Closed by 1b04d1cc6b04272c97d1276f1a3f546cdd16411c Closed by 1b04d1cc6b04272c97d1276f1a3f546cdd16411c

**Closed as completed by mirhagen** 2009-12-21 10:23 UTC
Labels: BUG, mirhagen
